edition = "2024"
fn_params_layout = "Vertical"
match_block_trailing_comma = true
merge_derives = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true
