[workspace]
members = ["x3f"]
resolver = "3"

[workspace.dependencies]
proptest = "1.10.0"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.package]
authors = []
edition = "2024"
publish = true
version = "0.0.5"
