[package]
authors.workspace = true
description = "SIGMA Foveon X3F RAW file parser"
edition.workspace = true
license = "MIT"
name = "x3f"
publish.workspace = true
readme = "README.md"
version = "0.0.2"

[dependencies]

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
